
// export const GET_RESTAURANTS_DATA_REQUEST = "GET_RESTAURANTS_DATA_REQUEST"
// export const GET_RESTAURANTS_DATA_SUCCESS = "GET_RESTAURANTS_DATA_SUCCESS"
// export const GET_RESTAURANTS_DATA_FAILURE = "GET_RESTAURANTS_DATA_FAILURE"


export const GET_RESTAURANTS_BY_CITY_REQUEST = "GET_RESTAURANTS_BY_CITY_REQUEST"
export const GET_RESTAURANTS_BY_CITY_SUCCESS = "GET_RESTAURANTS_BY_CITY_SUCCESS"
export const GET_RESTAURANTS_BY_CITY_FAILURE = "GET_RESTAURANTS_BY_CITY_FAILURE"


export const GET_RESTAURANTS_REQUEST = "GET_RESTAURANTS_REQUEST"
export const GET_RESTAURANTS_SUCCESS = "GET_RESTAURANTS_SUCCESS"
export const GET_RESTAURANTS_FAILURE = "GET_RESTAURANTS_FAILURE"


export const GET_MENU_DATA_REQUEST = "GET_MENU_DATA_REQUEST"
export const GET_MENU_DATA_SUCCESS = "GET_MENU_DATA_SUCCESS"
export const GET_MENU_DATA_FAILURE = "GET_MENU_DATA_FAILURE"

export const GET_SINGLE_RESTAURANT_NAME_REQUEST = "GET_SINGLE_RESTAURANT_NAME_REQUEST"
export const GET_SINGLE_RESTAURANT_NAME_SUCCESS = "GET_SINGLE_RESTAURANT_NAME_SUCCESS"
export const GET_SINGLE_RESTAURANT_NAME_FAILURE = "GET_SINGLE_RESTAURANT_NAME_FAILURE"

export const ADD_TO_CART_REQUEST = "ADD_TO_CART_REQUEST"
export const ADD_TO_CART_SUCCESS = "ADD_TO_CART_SUCCESS"
export const ADD_TO_CART_FAILURE = "ADD_TO_CART_FAILURE"

export const GET_CART_REQUEST = "GET_CART_REQUEST"
export const GET_CART_SUCCESS = "GET_CART_SUCCESS"
export const GET_CART_FAILURE = "GET_CART_FAILURE"

export const DELETE_ITEM_CART_REQUEST = "DELETE_ITEM_CART_REQUEST"
export const DELETE_ITEM_CART_SUCCESS = "DELETE_ITEM_CART_SUCCESS"
export const DELETE_ITEM_CART_FAILURE = "DELETE_ITEM_CART_FAILURE"



