
// export const GET_RESTAURANTS_DATA_REQUEST = "GET_RESTAURANTS_DATA_REQUEST"
// export const GET_RESTAURANTS_DATA_SUCCESS = "GET_RESTAURANTS_DATA_SUCCESS"
// export const GET_RESTAURANTS_DATA_FAILURE = "GET_RESTAURANTS_DATA_FAILURE"


export const GET_RESTAURANTS_BY_CITY_REQUEST = "GET_RESTAURANTS_BY_CITY_REQUEST"
export const GET_RESTAURANTS_BY_CITY_SUCCESS = "GET_RESTAURANTS_BY_CITY_SUCCESS"
export const GET_RESTAURANTS_BY_CITY_FAILURE = "GET_RESTAURANTS_BY_CITY_FAILURE"


export const GET_RESTAURANTS_REQUEST = "GET_RESTAURANTS_REQUEST"
export const GET_RESTAURANTS_SUCCESS = "GET_RESTAURANTS_SUCCESS"
export const GET_RESTAURANTS_FAILURE = "GET_RESTAURANTS_FAILURE"