export const GET_RESTAURANTS_OF_SHOPOWNER_REQUEST =
  "GET_RESTAURANTS_OF_SHOPOWNER_REQUEST";
export const GET_RESTAURANTS_OF_SHOPOWNER_SUCCESS =
  "GET_RESTAURANTS_OF_SHOPOWNER_SUCCESS";
export const GET_RESTAURANTS_OF_SHOPOWNER_FAILURE =
  "GET_RESTAURANTS_OF_SHOPOWNER_FAILURE";

export const ADD_RESTAURANT_OF_SHOPOWNER_REQUEST =
  "ADD_RESTAURANT_OF_SHOPOWNER_REQUEST";
export const ADD_RESTAURANT_OF_SHOPOWNER_SUCCESS =
  "ADD_RESTAURANT_OF_SHOPOWNER_SUCCESS";
export const ADD_RESTAURANT_OF_SHOPOWNER_FAILURE =
  "ADD_RESTAURANT_OF_SHOPOWNER_FAILURE";

export const EDIT_RESTAURANT_OF_SHOPOWNER_REQUEST =
  "EDIT_RESTAURANT_OF_SHOPOWNER_REQUEST";
export const EDIT_RESTAURANT_OF_SHOPOWNER_SUCCESS =
  "EDIT_RESTAURANT_OF_SHOPOWNER_SUCCESS";
export const EDIT_RESTAURANT_OF_SHOPOWNER_FAILURE =
  "EDIT_RESTAURANT_OF_SHOPOWNER_FAILURE";

export const DELETE_RESTAURANT_OF_SHOPOWNER_REQUEST =
  "DELETE_RESTAURANT_OF_SHOPOWNER_REQUEST";
export const DELETE_RESTAURANT_OF_SHOPOWNER_SUCCESS =
  "DELETE_RESTAURANT_OF_SHOPOWNER_SUCCESS";
export const DELETE_RESTAURANT_OF_SHOPOWNER_FAILURE =
  "DELETE_RESTAURANT_OF_SHOPOWNER_FAILURE";

export const GET_SINGLE_RESTAURANT_REQUEST = "GET_SINGLE_RESTAURANT_REQUEST";
export const GET_SINGLE_RESTAURANT_SUCCESS = "GET_SINGLE_RESTAURANT_SUCCESS";
export const GET_SINGLE_RESTAURANT_FAILURE = "GET_SINGLE_RESTAURANT_FAILURE";

export const GET_MENUES_OF_RESTAURANT_REQUEST =
  "GET_MENUES_OF_RESTAURANT_REQUEST";
export const GET_MENUES_OF_RESTAURANT_SUCCESS =
  "GET_MENUES_OF_RESTAURANT_SUCCESS";
export const GET_MENUES_OF_RESTAURANT_FAILURE =
  "GET_MENUES_OF_RESTAURANT_FAILURE";

export const ADD_NEW_MENU_REQUEST = "ADD_NEW_MENU_REQUEST";
export const ADD_NEW_MENU_SUCCESS = "ADD_NEW_MENU_SUCCESS";
export const ADD_NEW_MENU_FAILURE = "ADD_NEW_MENU_FAILURE";

export const UPDATE_MENU_REQUEST = "UPDATE_MENU_REQUEST";
export const UPDATE_MENU_SUCCESS = "UPDATE_MENU_SUCCESS";
export const UPDATE_MENU_FAILURE = "UPDATE_MENU_FAILURE";

export const DELETE_MENU_REQUEST = "DELETE_MENU_REQUEST";
export const DELETE_MENU_SUCCESS = "DELETE_MENU_SUCCESS";
export const DELETE_MENU_FAILURE = "UPDATE_MENU_FAILURE";
